version: '3'
# docker-compose --env-file .vps.env up

services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
#    env_file:
#      - .vps.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    container_name: ${DJANGO_CONTAINER_NAME}
    build: .
    #command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    command: "python educa/manage.py runserver 0.0.0.0:8000 --settings=educa.settings.prod_vps"
    restart: always
    env_file: .vps.env
    ports:
      - '8000:8000'
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod_vps
    depends_on: 
      - db
      - redis

  adminer:
    container_name: ${ADMINER_CONTAINER_NAME}
    image: adminer
    restart: always
    ports:
      - 8080:8080

#  nginx:
#    image: nginx:1.23.1
#    restart: always
#    volumes:
#      - ./config/nginx:/etc/nginx/templates
#      - .:/code
#    ports:
#      - "80:80"