version: '3'
services:
  db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:14.5
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .vps.env

  redis:
    container_name: ${REDIS_CONTAINER_NAME}
    image: redis:7.0.4
    restart: always
    volumes:
      - ./data/cache:/data

  web:
    container_name: ${DJANGO_CONTAINER_NAME}
    build: .
    #command: ["./wait-for-it.sh", "db:5432", "--", "uwsgi", "--ini", "/code/config/uwsgi/uwsgi.ini"]
    command: "python edu/educa/manage.py runserver 0.0.0.0"
    restart: always
    env_file: .vps.env
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=educa.settings.prod_vps
    depends_on: 
      - db
      - redis

#  nginx:
#    image: nginx:1.23.1
#    restart: always
#    volumes:
#      - ./config/nginx:/etc/nginx/templates
#      - .:/code
#    ports:
#      - "80:80"